- hosts: piloto
  become: true  
  tasks:
    - name:  
      lineinfile: Excluir linha1
        dest: [caminho do arquivo]
        regexp: '[Linha que deseja excluir]'
        state: absent
    - name: Excluir linha2
      lineinfile:
        dest: [caminho do arquivo]
        regex: '[Linha que deseja excluir]'
        state: absent
        
