- hosts: 
  become: true
  tasks:
    - name: Get information
      shell: "comand"
      register: commandname
    - name: Show information
      debug:
        msg: "{{commandname.stdout}}"
