# Playbook to disable or enable service
- hosts: 
  become: true
  tasks:
    - name: Desabilitar service
      service:
        name: [appname]
# "No" to disable, "yes" to enable 
        enabled: no
